config/routes.rb
Rails.application.routes.draw do
 
  resources :orderitems

  resources :orders do 
  resources :orderitems
  end
  devise_for :admins
  devise_for :users do
    resources :orders
   
end
get 'items/category/:id' => 'items#category'
get '/checkout' => 'cart#createOrder'
  get 'site/home'

  get 'site/about'

  get 'site/services'

  get 'site/contact'

get 'cart/index'
get 'site/about' => 'site#about'
get 'site/contact' => 'site#contact'
get 'site/home' => 'site#home'

  get '/cart' => 'cart#index' 

get '/cart/:id' => 'cart#add'

get'/cart/remove/:id' => 'cart#remove'
get '/clear' => 'cart#clear'
  resources :items

 root 'site#home'

end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
  before_action :set_orderitem, only: [:show, :edit, :update, :destroy]
 before_action  :authenticate_admin!, only: [ :edit, :update, ]

  # GET /orderitems
  # GET /orderitems.json
  def index
    @orderitems = Orderitem.all
  end

  # GET /orderitems/1
  # GET /orderitems/1.json
  def show
  end

  # GET /orderitems/new
  def new
    @orderitem = Orderitem.new
  end

  # GET /orderitems/1/edit
  def edit
  end

  # POST /orderitems
  # POST /orderitems.json
  def create
    @orderitem = Orderitem.new(orderitem_params)

    respond_to do |format|
      if @orderitem.save
        format.html { redirect_to @orderitem, notice: 'Orderitem was successfully created.' }
        format.json { render :show, status: :created, location: @orderitem }
      else
        format.html { render :new }
        format.json { render json: @orderitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderitems/1
  # PATCH/PUT /orderitems/1.json
  def update
    respond_to do |format|
      if @orderitem.update(orderitem_params)
        format.html { redirect_to @orderitem, notice: 'Orderitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @orderitem }
      else
        format.html { render :edit }
        format.json { render json: @orderitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderitems/1
  # DELETE /orderitems/1.json
  def destroy
    @orderitem.destroy
    respond_to do |format|
      format.html { redirect_to orderitems_url, notice: 'Orderitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderitem
      @orderitem = Orderitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orderitem_params
      params.require(:orderitem).permit(:item_id, :product, :colour, :description, :quantity, :price, :order_id)
    end

end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/views/orderitems/_form.html.erb
<%= form_for(@orderitem) do |f| %>
  <% if @orderitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orderitem.errors.count, "error") %> prohibited this orderitem from being saved:</h2>

      <ul>
      <% @orderitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.text_field :order_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orderitems/edit.html.erb
<% if admin_signed_in? %>
 <div>You are currently signed in as: <%= current_admin.email %> (<%= link_to 'Sign out', destroy_admin_session_path, :method => :delete
%>)</div>
<% end %>  

<h1>Editing Orderitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @orderitem %> |
<%= link_to 'Back', orderitems_path %>

app/views/orderitems/index.html.erb
<h1>Your Orders</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Product</th>
      <th>Colour</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <% @orderitems.each do |orderitem| %>
      <tr>
        <td><%= orderitem.item_id %></td>
        <td><%= orderitem.product %></td>
        <td><%= orderitem.colour %></td>
        <td><%= orderitem.description %></td>
        <td><%= orderitem.quantity %></td>
        <td><%= (orderitem.price * orderitem.quantity)  %></td>
        <td><%= orderitem.order %></td>
       
        <td><%= link_to 'Delete Item', orderitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Add more items', :controller => :items %>
|

<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="rodwardle-facilitator@icloud.com">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

app/views/orderitems/new.html.erb
<% if admin_signed_in? %>
 <div>You are currently signed in as: <%= current_admin.email %> (<%= link_to 'Sign out', destroy_admin_session_path, :method => :delete
%>)</div>
<% end %>  
<h1>New Orderitem</h1>

<%= render 'form' %>

<%= link_to 'Back', orderitems_path %>

app/views/orderitems/show.html.erb
<% if admin_signed_in? %>
 <div>You are currently signed in as: <%= current_admin.email %> (<%= link_to 'Sign out', destroy_admin_session_path, :method => :delete
%>)</div>
<% end %>  
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @orderitem.item_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @orderitem.product %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @orderitem.colour %>
</p>

<p>
  <strong>Description:</strong>
  <%= @orderitem.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @orderitem.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @orderitem.price %>
</p>

<p>
  <strong>Order:</strong>
  <%= @orderitem.order %>
</p>

<%= link_to 'Edit', edit_orderitem_path(@orderitem) %> |
<%= link_to 'Back', orderitems_path %>