config/routes.rb
Rails.application.routes.draw do
 
  resources :orderitems

  resources :orders do 
  resources :orderitems
  end
  devise_for :admins
  devise_for :users do
    resources :orders
   
end
get 'items/category/:id' => 'items#category'
get '/checkout' => 'cart#createOrder'
  get 'site/home'

  get 'site/about'

  get 'site/services'

  get 'site/contact'

get 'cart/index'
get 'site/about' => 'site#about'
get 'site/contact' => 'site#contact'
get 'site/home' => 'site#home'

  get '/cart' => 'cart#index' 

get '/cart/:id' => 'cart#add'

get'/cart/remove/:id' => 'cart#remove'
get '/clear' => 'cart#clear'
  resources :items

 root 'site#home'

end

app/models/item.rb
class Item < ActiveRecord::Base

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
 before_action  :authenticate_admin!, only: [ :new,:edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def category
    @item = Item.find_all_by_category(params[:id])
    @category = params[:id]
    
  respond_to do |format|
    format.html {index.html.erb}
    format.json {render json:@item}
  end  
  end
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:product, :description, :price, :image, :category, :colour)
    end
end

 def index
  @items = Item.search(params[:search])
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/category.html.erb
<% if admin_signed_in? %>
 <div>You are in Administration mode (<%= link_to 'Sign out', destroy_admin_session_path, :method => :delete
%>)</div>
<% end %>   
<h1>Our Products</h1>
<br>
<h2><% =@category %></h2>
<table class="catalog">
<% @items.each do |item| %> <tr>
<td>
<div class="image">
<%= link_to (image_tag item.image, :style => "height:100px"), item %> </div>
</td> <td>
<div class="title">
Product: <%= h item.product %>
</div>
<div class="colour">
Colour: <%= h item.colour %>
</div>
<div class="category">
Category: <%= h item.category %>
</div>
<div class="description">
Description: <%=h item.description %> </div>
<div class="price">
Our Price: <%= number_to_currency(item.price, :unit => "€") %>
<br >


</div>

<div class="links">
<% if admin_signed_in? %>

| <%= link_to 'Edit', edit_item_path(item) %> |
<%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %> | 
<% else %>
<a href="/cart/<%= item.id %>">Add to Cart</a><br><br>
<% end %>
</div>
---------------------------
</td> </tr>
<% end %> </table>
<% if admin_signed_in? %>
<p><%= link_to '(New item ->)', new_item_path %></p>
<% end %>

app/views/items/edit.html.erb
<% if admin_signed_in? %>
 <div>You are currently signed in as: <%= current_admin.email %> (<%= link_to 'Sign out', destroy_admin_session_path, :method => :delete
%>)</div>
<% end %>   

<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% if admin_signed_in? %>
 <div>You are in Administration mode (<%= link_to 'Sign out', destroy_admin_session_path, :method => :delete
%>)</div>
<% end %>  

<h1>Our Products</h1>
<br>
 <%= form_tag(items_url, method: :get, role: 'search') do %>
 
 Product Search:  <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
<% end %>
<br>
<table class="catalog">
<% @items.each do |item| %> <tr>
<td>
<div class="image">
<%= link_to (image_tag item.image, :style => "height:100px"), item %> </div>
</td> <td>
<div class="title">
Product: <%= h item.product %>
</div>
<div class="colour">
Colour: <%= h item.colour %>
</div>
<div class="category">
Category: <%= h item.category %>
</div>
<div class="description">
Description: <%=h item.description %> </div>
<div class="price">
Our Price: <%= number_to_currency(item.price, :unit => "€") %>
<br >


</div>

<div class="links">
<% if admin_signed_in? %>

| <%= link_to 'Edit', edit_item_path(item) %> |
<%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %> | 
<% else %>
<a href="/cart/<%= item.id %>">Add to Cart</a><br><br>
<% end %>
</div>
---------------------------
</td> </tr>
<% end %> </table>
<% if admin_signed_in? %>
<p><%= link_to '(New item ->)', new_item_path %></p>
<% end %>

app/views/items/new.html.erb
<% if admin_signed_in? %>
 <div>You are currently signed in as: <%= current_admin.email %> (<%= link_to 'Sign out', destroy_admin_session_path, :method => :delete
%>)</div>
<% end %>   
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @item.product %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @item.image %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @item.colour %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>